### ISSUE TITLE
[CFP] - 12º Live ReactJS Ceará

### ISSUE THREAD

**Issue by cicerohen** [reactjs-ceara/agenda#15]
# [CFP] - 12º Live ReactJS Ceará

Data e horário: **7 de outubro**, às 19h, **online** no  [Discord](https://discord.gg/bz55hDJQRh) da comunidade.
Submeta sua palestra(**máximo de 30 minutos**) através dos comentários, seguindo o formato:

**Título**
**Duração(HH:MM)**
**Descrição curta**
**Descrição longa**
 
**DICA:**

Algumas sugestões da comunidade sobre tópicos interessantes para palestras
https://docs.google.com/spreadsheets/d/15vhCbD6LZwJageJO0OJa9IRFvE4zzBCMGod48UDqUn8/edit?usp=sharing

**Comment by ismaelash** [comment]
Conteúdo 3D com ReactJS
Duração(00:30)
Nessa palestra, vou mostrar como exibir modelos 3D na web utilizando ReactJS

**Comment by cicerohen** [comment]
###  Micro Frontends
Abordagens Práticas



30min

Nesta irei discutir sobre micro frontends seus porquês e  também sobre algumas abordagens práticas para estruturação desta arquitetura.

**Comment by ismaelash** [comment]
A dor de cabeça de criar um chat, o lado por tras das mensagens
Duração(00:30)
Nessa palestra, vou falar sobre o case de cria um chat(frontend e backend) para evento virtual online. 
Compartilhar as dores de cabeça e o por que não fazer um chat do zero.

**Comment by danielmartins04** [comment]
Conceitos básicos e gerais do react, explicação sobre a estrutura geral de um projeto simples para quem está iniciando.
Duração(00:30)
Nessa palestra vou apresentar conceitos essenciais para quem está iniciando nesse mundo de SPA com React, mostrando a estrutura de um projeto real que implemente esse conceitos. Pretendo também citar e explicar temas que são mais avançados, como forma de demonstrar o que é possível desenvolver e quais possibilidades que a biblioteca nos oferece.
