### ISSUE TITLE
[CFP] - 4º Meetup ReactJS Ceará

### ISSUE THREAD

**Issue by cicerohen** [reactjs-ceara/agenda#24]
### MAIS UM!!!

No dia  **25 de junho** a patir das  **9h** estaremos novamente na [Digital College](https://www.instagram.com/digitalcollegebr/)  realizando o 4º meetup ReactJS Ceará.

Envie sua talk no seguinte formato:

**Título**
**Duração(HH:MM)**
**Descrição curta**
**Descrição longa**

**Comment by tony-matheus** [comment]
The power of the styled-system

Description: uma breve introdução sobre uma biblioteca poderosa de estilização!

Duração 20-30min

**Comment by abdielbrilhante** [comment]
**Infraestrutura para aplicações Frontend**

30 minutos

Uma rápida explicação (com exemplos) de como funciona a infra necessária para servir Single Page Applications

Além de entender onde se encaixa a infraestrutura no processo de desenvolvimento e da importância de ter um conhecimento básico dela como desenvolvedores frontend/React, veremos como geralmente é a configuração de uma aplicação React simples na AWS e um exemplo de um problema comum relacionado a essa infraestrutura.

**Comment by gleysonlf** [comment]
# Next.js: por que usar?
**Duração(HH:MM):** 00:30
## Entendendo Next.js e aplicando suas funcionalidades

> Nesta sessão vamos falar sobre o que é o **Next.js** e o que nos motiva a usar esse framework. Entender um pouco sobre SPA, SSR, SSG e como cada um deles tem uma relevância para aplicações web. Veremos ainda alguns recursos disponibilizados por esta solução que facilitam e muito nosso dia a dia.

**Comment by rubenspgcavalcante** [comment]
# Mercado Internacional e Como Se Preparar Para Uma Entrevista Para Fora do Brasil

Duração(HH:MM): 00:30

Com 5 anos e meio trabalhando na europa, quero trazer minhas experiências sobre trabalhar fora, um pouco sobre a empresas que passei (Zalando, Grupo OLX e agora Meta) e como se preparar para uma entrevista internacional (na minha experiência de entrevistado e no meu ponto de vista como entrevistador), incluindo um pouco do processo de dois big techies: Meta e Amazon.
