### ISSUE TITLE
[CFP] - 1º Bootcamp ReactJS Ceará

### ISSUE THREAD

**Issue by cicerohen** [reactjs-ceara/agenda#28]
E pra janeiro de 2023  teremos um evento um pouco difrente: Bootcamps para capacitação teórica e prática  na criação de pequenas aplicações web ou mobile.

Para os interessados em ministrar um bootcamp,  comente na issue seguindo o seguinte formato:

**Título do bootcamp**
**Duração(HH:MM)**
**Objetivo do bootcamp( o que será aprendido)**

**Comment by zorasantos** [comment]
Título do bootcamp => Feature toggle(flag) com react e firebase
Duração(HH:MM) => 1h:30m?
Objetivo do bootcamp( o que será aprendido) =>  Usar a técnica do feature toggle para habilitar e desabilitar recursos e funcionalidades em um sistema sem alteração de código e em tempo real.

**Comment by oismaelash** [comment]
Título do bootcamp:::
Fazendo deploy de app React.js no AWS Amplify

Duração(HH:MM):::
00:40

Objetivo do bootcamp( o que será aprendido):::
Neste bootcamp, iremos fazer deploy de uma aplicação React.js dentro do AWS Amplify.
AWS Amplify serviço para subirmos aplicaçoes frontend e traz diversos recursos, como:
CI/CD, configuraçao de dominios, metricas entre outros

**Comment by oismaelash** [comment]
Título do bootcamp:::
Criando aplicação de realidade aumentada usando React.js

Duração(HH:MM):::
00:40

Objetivo do bootcamp( o que será aprendido):::
Neste bootcamp, iremos criar um site onde ira ter realidade aumentada.
Metaverso está em alta, e realidade aumentada é uma das portas de entrada, 
iremos ver as principais libs de realidade aumentada para web e ao final, 
iremos ter nossa pagina web com realidade aumentada com deploy na AWS

**Comment by oismaelash** [comment]
Título do bootcamp:::
Criando um bom Linkedin para desenvolvedor

Duração(HH:MM):::
00:40

Objetivo do bootcamp( o que será aprendido):::
Neste bootcamp, iremos melhorar o linkedin de cada pessoa participante
Irei abordar os principais pontos que atraem recrutadores para seu linkedin e enviar vagas para voce.
Irei trazer dicas caso voce seja iniciante ou senior, para conseguir aumentar o seu proprio valor

**Comment by cicerohen** [comment]
### Estruturação de projetos ReactJS

Neste bootcamp iremos aprender como organizar arquivos, pastas, componentes, hooks, etc. 

Duração: 1h

**Comment by AbraaoAlves** [comment]
## Criando uma testes automatizados para meu app

Neste bootcamp iremos juntos aprender criar uma suíte de testes para nosso webapp, transformando requisitos de sistema em documentação autoexecutável.

**Público-alvo**: Iniciante ou Juniors
**Duração**: 1h:30min

**Comment by EnzoPortela** [comment]
### O que você deveria saber antes de pôr as mãos em ReactJS
Neste bootcamp, iremos passar por conceitos fundamendais de Javascript e React que você deve (ou deveria) conhecer antes de começar um projeto.

**Público-alvo: Iniciantes e/ou Júniors**

**Duração: 1hr**

**Comment by CauanDZN** [comment]
> ## Debug em aplicações React Native
> Neste bootcamp, iremos juntos aprender a como debugar uma aplicação React Native, quais ferramentas utilizar e no que se preocupar ao realizar o debug!
> 
> **Público-alvo**: Iniciantes ou Júnior's 
> **Duração**: 1h:00min

**Comment by CauanDZN** [comment]
## Animações no React Native
Animações são muito importantes para destacar sua aplicação e proporcionar um diferencial na experiência do seu usuário.
 No React Native, contamos com duas grandes referências quando o assunto são bibliotecas de animação. Iremos, nesse bootcamp, explorar a Reanimated v2 e o Moti para entender onde melhor aplicar cada uma delas!

**Público-alvo:** Iniciantes e/ou Júnior's

**Duração:** 1h:00min

**Comment by CauanDZN** [comment]
## Deploy de aplicações React Native
Quando chega o momento de disponibilizar os seus Apps para os seus usuários... É gratificante. Nesse bootcamp, vamos entender as técnicas de publicação de apps e compreender como realizar o deploy de nossas aplicações, aprenderemos a enviar o build Android à Google Play Store e disponibilizar nossa aplicação para o mundo!

**Público-alvo:** Iniciantes e/ou Júnior's
**Duração:** 1h:30min
