### ISSUE TITLE
[CFP] 2º ReactJS Ceará Labs

### ISSUE THREAD

**Issue by cicerohen** [reactjs-ceara/agenda#32]
O **ReactJS Ceará Labs** é um evento **online**(pelo **Discord**)  e **gratuito** onde  qualquer pessoa pode, em **40 minutos**,  mostrar alguma abordagem prática com ferramentas e/ou linguagens do mundo Front-end.

Para os interessados em mostrar algo prático comente na issue seguindo o formato abaixo:

**Título**: (ex: Criando um simples hooks para fazer requisições HTTP no ReactJS)
**Descrição**: (ex: Neste lab irei mostrar como manusear requisições HTTP utilizando axios e  ReactJS Hooks)

**As apresentações  serão escolhidas por ordem de votação utilizando o ❤️** 

 **A apresentação deverá ser de  no máximo 40 minutos.**

**Comment by abdielbrilhante** [comment]
**Entendendo a propriedade `key` no React**

Veremos uma aplicação de exemplo que ilustra os problemas que a ausência de uma `key` causa durante a renderização de listas, e no processo poderemos entender parte das otimizações que o React faz durante atualizações de componentes.
