### ISSUE TITLE
[CFP] - 6º Meetup ReactJS Ceará

### ISSUE THREAD

**Issue by cicerohen** [reactjs-ceara/agenda#34]
# [CFP] - 6º Meetup ReactJS Ceará 

Dia **22 de abril**, às 9h, estaremos na Digital College, agora na **sede Sul**, no WSTC, na Av. W. Soares, Fortaleza. 

Envie sua talk no seguinte formato:

**Título**
**Duração(HH:MM)**
**Descrição curta**
**Descrição longa**

**Comment by cicerohen** [comment]
###  Abordagem utility-fist com TailwindCSS
_00:40h_

Nesta talk irei falar sobre como organizar projetos  ReactJS utilizando a abordagem utility-first com TailwindCSS e como desenvolver um projeto ReactJS com uma visão de camadas, separando resonsabilidades, etc, etc.

**Comment by CauanDZN** [comment]
**A nova documentação do React: o que mudou?**

_00:40h_

Nessa talk, discutiremos juntos sobre a nova documentação do React: como as novas recomendações impactam nas gerações seguintes de desenvolvimento da tecnologia.

**Comment by AbraaoAlves** [comment]
## O X do MDX
 _00:40h_

Nessa talk @KevinDik e eu, apresentaremos o que é MDX e o universo de possibilidades que ele nos trás para a criação de blogs, apresentações, sites, documentações e muito mais!

.
